sudo: required

language: java
jdk:
  - openjdk8

before_script:
  - wget http://services.gradle.org/distributions/gradle-5.5.1-bin.zip
  - unzip gradle-5.5.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.5.1
  - export PATH=$GRADLE_HOME/bin:$PATH

addons:
  sonarcloud:
    organization: "wa-01"
    token:
      secure: $SONAR_TOKEN

script:
  - gradle test
  - sonar-scanner
  - gradle check

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
